### ISSUE TITLE
Error desconocido docker

### ISSUE THREAD

**Issue by Cadagan** [IIC2143-2019-2/proyecto#97]
Al intentar (fallidamente) subir mi app a heroku, de alguna forma mi app dejo de funcionar en el localhost tambien, por lo que volvi a un commit anterior donde si funcionaba la app.

El problema es que ahora tampoco corre, y al correr el `sudo docker-compose build` me arroja el siguiente error:

> db uses an image, skipping
Building web
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 249, in build
    build_args=build_args)
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 343, in build
    service.build(no_cache, pull, force_rm, build_args)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 923, in build
    shmsize=parse_bytes(build_opts.get('shm_size')) if build_opts.get('shm_size') else None,
  File "/usr/lib/python2.7/dist-packages/docker/api/build.py", line 238, in build
    self._set_auth_headers(headers)
  File "/usr/lib/python2.7/dist-packages/docker/api/build.py", line 285, in _set_auth_headers
    self._auth_configs, registry
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 97, in resolve_authconfig
    authconfig, registry, store_name
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 142, in _resolve_authconfig_credstore
    'Credentials store error: {0}'.format(repr(e))
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-secretservice exited with "Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached".',)

Obviamente para peor esto me pasa el día anterior a la entrega, perdiendo todo mi trabajo y para peor mi grupo me abandono (no hicieron nada para esta entrega). Si algun alma piadosa sabe como solucionarlo, se agradeceria infinitamente su ayuda, ya que lamentablemente la unica persona que me ha ayudado ha sido el ayudante a cargo de mi "grupo" :(

**Comment by daleal** [comment]
Hola! Corre el comando `docker login`. Probablemente tus credenciales expiraron y debes renovarlas

**Comment by Cadagan** [comment]
Hola! disculpa lo tarde, finalmente en esa instancia lo que hice fue simplemente volver a una version anterior de github. (gracias a Jero que me ayudo)

El problema es que ahora una versión con avances es la que pulleo y me sigue apareciendo el mismo problema, de casualidad no le paso a alguien mas? :(

**Comment by movaldivia** [comment]
A mí en lo personal, nunca me ha pasado. Aquí parece que una persona lo pudo solucionar eso si.
https://stackoverflow.com/questions/50151833/cannot-login-to-docker-account

**Comment by daleal** [comment]
Lo que yo creo que está pasando es que las credenciales en tu computador expiraron, por lo que no puedes pullear imágenes de docker. Sin embargo, al volver a una versión anterior la imágen ya estaba buildeada, por lo que el problema no se repite. Intenta ver si la respuesta de @movaldivia soluciona tu problema. Si no, ejecuta `docker login`, introduce tus credenciales y vuelve a intentarlo.
